# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.listWidget_PDF = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_PDF.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.listWidget_PDF.setMovement(QtWidgets.QListView.Static)
        self.listWidget_PDF.setObjectName("listWidget_PDF")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listWidget_PDF.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listWidget_PDF.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listWidget_PDF.addItem(item)
        self.gridLayout.addWidget(self.listWidget_PDF, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAdd_PDFs = QtWidgets.QAction(MainWindow)
        self.actionAdd_PDFs.setObjectName("actionAdd_PDFs")
        self.actionCombine_PDFs_and_Save = QtWidgets.QAction(MainWindow)
        self.actionCombine_PDFs_and_Save.setObjectName("actionCombine_PDFs_and_Save")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionAdd_PDFs)
        self.menuFile.addAction(self.actionCombine_PDFs_and_Save)
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MFMC MergePDF"))
        __sortingEnabled = self.listWidget_PDF.isSortingEnabled()
        self.listWidget_PDF.setSortingEnabled(False)
        item = self.listWidget_PDF.item(0)
        item.setText(_translate("MainWindow", "Item A"))
        item = self.listWidget_PDF.item(1)
        item.setText(_translate("MainWindow", "Item B"))
        item = self.listWidget_PDF.item(2)
        item.setText(_translate("MainWindow", "Item C"))
        self.listWidget_PDF.setSortingEnabled(__sortingEnabled)
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionAdd_PDFs.setText(_translate("MainWindow", "Add PDFs"))
        self.actionCombine_PDFs_and_Save.setText(_translate("MainWindow", "Combine PDFs and Save"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
